language: scala
scala:
  - 2.11.5
  - 2.10.4
jdk:
  - oraclejdk8
  - oraclejdk7
script: sbt ++$TRAVIS_SCALA_VERSION compile test package
matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk7
    - scala: 2.10.4
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f8c76df769344205cb16
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
